### PR TITLE
Create Join a vc

### PR DESCRIPTION
**Pull request by ashadamn**
Please label it as hacktoberfest

### CODE REVIEW

**Comment by HashimTheArab** [comment]
Ain't no way

**Comment by TacoError** [comment]
E961407A-67E2-4294-82A0-AEF08C097164

**Review by TacoError — CHANGES_REQUESTED** [review]
what the fuck is wrong with you

**Comment by Theflashiscool2** [comment]
Thank you for this great JavaScript contribution and a golang discord bot

**Pull request closed without merging**
